"""create club settings table

Revision ID: 151e83bf38e7
Revises: 1b1918681ca7
Create Date: 2026-07-13 15:21:22.005005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151e83bf38e7'
down_revision: Union[str, Sequence[str], None] = '1b1918681ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('club_name', sa.String(length=255), server_default='CyberClub', nullable=False),
    sa.Column('branch', sa.String(length=255), server_default='#1', nullable=False),
    sa.Column('lottery_ticket_price', sa.Numeric(precision=12, scale=2), server_default='85.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_settings')
    # ### end Alembic commands ###
