"""create action logs table

Revision ID: 1b1918681ca7
Revises: a5ec30843254
Create Date: 2026-07-12 21:08:55.827105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b1918681ca7'
down_revision: Union[str, Sequence[str], None] = 'a5ec30843254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_created_at'), 'action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_logs_entity_id'), 'action_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_action_logs_entity_type'), 'action_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_action_logs_event_type'), 'action_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_logs_event_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_entity_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_entity_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_created_at'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
