"""add ticket price to prizes

Revision ID: 5b16e12a9335
Revises: 151e83bf38e7
Create Date: 2026-07-16 11:04:01.712950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b16e12a9335'
down_revision: Union[str, Sequence[str], None] = '151e83bf38e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('ticket_price', sa.Numeric(precision=12, scale=2), server_default='85.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prizes', 'ticket_price')
    # ### end Alembic commands ###
