"""create lightshell import tables

Revision ID: 64b54cd4ceb9
Revises: bb06f6d33e42
Create Date: 2026-07-12 11:01:15.483033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b54cd4ceb9'
down_revision: Union[str, Sequence[str], None] = 'bb06f6d33e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightshell_inventory_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('matched_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unresolved_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('created_items >= 0', name='ck_lightshell_import_created_items'),
    sa.CheckConstraint('matched_items >= 0', name='ck_lightshell_import_matched_items'),
    sa.CheckConstraint('total_items >= 0', name='ck_lightshell_import_total_items'),
    sa.CheckConstraint('unresolved_items >= 0', name='ck_lightshell_import_unresolved_items'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lightshell_product_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_source_name', sa.String(length=255), nullable=False),
    sa.Column('source_category', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lightshell_product_mappings_normalized_source_name'), 'lightshell_product_mappings', ['normalized_source_name'], unique=True)
    op.create_index(op.f('ix_lightshell_product_mappings_product_id'), 'lightshell_product_mappings', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lightshell_product_mappings_product_id'), table_name='lightshell_product_mappings')
    op.drop_index(op.f('ix_lightshell_product_mappings_normalized_source_name'), table_name='lightshell_product_mappings')
    op.drop_table('lightshell_product_mappings')
    op.drop_table('lightshell_inventory_imports')
    # ### end Alembic commands ###
