"""create prizes table

Revision ID: a5ec30843254
Revises: 64b54cd4ceb9
Create Date: 2026-07-12 12:53:34.084607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ec30843254'
down_revision: Union[str, Sequence[str], None] = '64b54cd4ceb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prizes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('written_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'written_off')", name='ck_prizes_status_valid'),
    sa.CheckConstraint('quantity > 0', name='ck_prizes_quantity_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prizes_employee_id'), 'prizes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_prizes_product_id'), 'prizes', ['product_id'], unique=False)
    op.create_index(op.f('ix_prizes_status'), 'prizes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prizes_status'), table_name='prizes')
    op.drop_index(op.f('ix_prizes_product_id'), table_name='prizes')
    op.drop_index(op.f('ix_prizes_employee_id'), table_name='prizes')
    op.drop_table('prizes')
    # ### end Alembic commands ###
