"""create debts table

Revision ID: bb06f6d33e42
Revises: b4ca789f3e05
Create Date: 2026-07-11 19:46:35.046395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb06f6d33e42'
down_revision: Union[str, Sequence[str], None] = 'b4ca789f3e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'paid')", name='ck_debts_status_valid'),
    sa.CheckConstraint('quantity > 0', name='ck_debts_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_debts_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_employee_id'), 'debts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_debts_product_id'), 'debts', ['product_id'], unique=False)
    op.create_index(op.f('ix_debts_status'), 'debts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debts_status'), table_name='debts')
    op.drop_index(op.f('ix_debts_product_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_employee_id'), table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###
